name:  ElementFilter
author:  davidwalsh
current:  1.1
category:  Utilities
tags:  [element,filter,search]
docs:  http://davidwalsh.name/plugin-element-filter
demo:  http://davidwalsh.name/plugin-element-filter
